/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iSaleManagerSol from "./ISaleManager.sol";
export type { iSaleManagerSol };
import type * as saleManagerSol from "./SaleManager.sol";
export type { saleManagerSol };
