/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FakeChainlinkOracle } from "./FakeChainlinkOracle";
export type { FakeEthOracle } from "./FakeEthOracle";
export type { FakeUsdcOracle } from "./FakeUsdcOracle";
export type { FakeUsdtOracle } from "./FakeUsdtOracle";
