/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export interface SaleManager_v_1_2Interface extends utils.Interface {
  functions: {
    "VERSION()": FunctionFragment;
    "_isAllowed(bytes32,address,bytes32[])": FunctionFragment;
    "buy(bytes32,bytes32[])": FunctionFragment;
    "buy(bytes32,uint256,bytes32[])": FunctionFragment;
    "generateRandomishValue(bytes32)": FunctionFragment;
    "getAdmin(bytes32)": FunctionFragment;
    "getBought(bytes32,address)": FunctionFragment;
    "getClaimManager(bytes32)": FunctionFragment;
    "getDecimals(bytes32)": FunctionFragment;
    "getEndTime(bytes32)": FunctionFragment;
    "getFairQueueTime(bytes32,address)": FunctionFragment;
    "getLatestPrice()": FunctionFragment;
    "getMaxQueueTime(bytes32)": FunctionFragment;
    "getMerkleRoot(bytes32)": FunctionFragment;
    "getPrice(bytes32)": FunctionFragment;
    "getPriceOracle()": FunctionFragment;
    "getRandomValue(bytes32)": FunctionFragment;
    "getRecipient(bytes32)": FunctionFragment;
    "getSaleBuyLimit(bytes32)": FunctionFragment;
    "getSpent(bytes32,address)": FunctionFragment;
    "getStartTime(bytes32)": FunctionFragment;
    "getTotalSpent(bytes32)": FunctionFragment;
    "getUri(bytes32)": FunctionFragment;
    "getUserBuyLimit(bytes32)": FunctionFragment;
    "isOpen(bytes32)": FunctionFragment;
    "isOver(bytes32)": FunctionFragment;
    "nativeToPaymentToken(uint256)": FunctionFragment;
    "newSale(address,bytes32,uint256,uint256,uint256,uint256,uint160,string,uint256,uint8)": FunctionFragment;
    "paymentToken()": FunctionFragment;
    "paymentTokenDecimals()": FunctionFragment;
    "recoverERC20(bytes32,address,uint256)": FunctionFragment;
    "registerClaimManager(bytes32,address)": FunctionFragment;
    "saleCount()": FunctionFragment;
    "setEnd(bytes32,uint256)": FunctionFragment;
    "setMaxQueueTime(bytes32,uint160)": FunctionFragment;
    "setMerkleRoot(bytes32,bytes32)": FunctionFragment;
    "setStart(bytes32,uint256)": FunctionFragment;
    "setUriAndMerkleRoot(bytes32,bytes32,string)": FunctionFragment;
    "spentToBought(bytes32,uint256)": FunctionFragment;
    "totalSpent()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "VERSION"
      | "_isAllowed"
      | "buy(bytes32,bytes32[])"
      | "buy(bytes32,uint256,bytes32[])"
      | "generateRandomishValue"
      | "getAdmin"
      | "getBought"
      | "getClaimManager"
      | "getDecimals"
      | "getEndTime"
      | "getFairQueueTime"
      | "getLatestPrice"
      | "getMaxQueueTime"
      | "getMerkleRoot"
      | "getPrice"
      | "getPriceOracle"
      | "getRandomValue"
      | "getRecipient"
      | "getSaleBuyLimit"
      | "getSpent"
      | "getStartTime"
      | "getTotalSpent"
      | "getUri"
      | "getUserBuyLimit"
      | "isOpen"
      | "isOver"
      | "nativeToPaymentToken"
      | "newSale"
      | "paymentToken"
      | "paymentTokenDecimals"
      | "recoverERC20"
      | "registerClaimManager"
      | "saleCount"
      | "setEnd"
      | "setMaxQueueTime"
      | "setMerkleRoot"
      | "setStart"
      | "setUriAndMerkleRoot"
      | "spentToBought"
      | "totalSpent"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "VERSION", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "_isAllowed",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "buy(bytes32,bytes32[])",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "buy(bytes32,uint256,bytes32[])",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "generateRandomishValue",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getAdmin",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getBought",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimManager",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getDecimals",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getEndTime",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getFairQueueTime",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMaxQueueTime",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getMerkleRoot",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getPrice",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getPriceOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRandomValue",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecipient",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getSaleBuyLimit",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getSpent",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getStartTime",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalSpent",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getUri",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserBuyLimit",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "isOpen",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "isOver",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "nativeToPaymentToken",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "newSale",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "paymentToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "paymentTokenDecimals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recoverERC20",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "registerClaimManager",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "saleCount", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setEnd",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxQueueTime",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setMerkleRoot",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "setStart",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setUriAndMerkleRoot",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "spentToBought",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSpent",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "VERSION", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "_isAllowed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "buy(bytes32,bytes32[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buy(bytes32,uint256,bytes32[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "generateRandomishValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAdmin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBought", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getClaimManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDecimals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEndTime", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getFairQueueTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMaxQueueTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMerkleRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPriceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRandomValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSaleBuyLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSpent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getStartTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalSpent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getUri", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserBuyLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isOpen", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isOver", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nativeToPaymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "newSale", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "paymentTokenDecimals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recoverERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerClaimManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "saleCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setEnd", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMaxQueueTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMerkleRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setStart", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setUriAndMerkleRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "spentToBought",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalSpent", data: BytesLike): Result;

  events: {
    "Buy(bytes32,address,uint256,bool,bytes32[])": EventFragment;
    "Deploy(address,uint8,address)": EventFragment;
    "NewSale(bytes32,bytes32,address,address,uint256,uint256,uint256,uint256,uint256,string,uint256,uint8)": EventFragment;
    "RegisterClaimManager(bytes32,address)": EventFragment;
    "UpdateEnd(bytes32,uint256)": EventFragment;
    "UpdateMaxQueueTime(bytes32,uint256)": EventFragment;
    "UpdateMerkleRoot(bytes32,bytes32)": EventFragment;
    "UpdateStart(bytes32,uint256)": EventFragment;
    "UpdateUri(bytes32,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Buy"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Deploy"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewSale"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RegisterClaimManager"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdateEnd"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdateMaxQueueTime"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdateMerkleRoot"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdateStart"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdateUri"): EventFragment;
}

export interface BuyEventObject {
  saleId: string;
  buyer: string;
  value: BigNumber;
  native: boolean;
  proof: string[];
}
export type BuyEvent = TypedEvent<
  [string, string, BigNumber, boolean, string[]],
  BuyEventObject
>;

export type BuyEventFilter = TypedEventFilter<BuyEvent>;

export interface DeployEventObject {
  paymentToken: string;
  paymentTokenDecimals: number;
  priceOracle: string;
}
export type DeployEvent = TypedEvent<
  [string, number, string],
  DeployEventObject
>;

export type DeployEventFilter = TypedEventFilter<DeployEvent>;

export interface NewSaleEventObject {
  saleId: string;
  merkleRoot: string;
  recipient: string;
  admin: string;
  saleBuyLimit: BigNumber;
  userBuyLimit: BigNumber;
  maxQueueTime: BigNumber;
  startTime: BigNumber;
  endTime: BigNumber;
  uri: string;
  price: BigNumber;
  decimals: number;
}
export type NewSaleEvent = TypedEvent<
  [
    string,
    string,
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    BigNumber,
    number
  ],
  NewSaleEventObject
>;

export type NewSaleEventFilter = TypedEventFilter<NewSaleEvent>;

export interface RegisterClaimManagerEventObject {
  saleId: string;
  claimManager: string;
}
export type RegisterClaimManagerEvent = TypedEvent<
  [string, string],
  RegisterClaimManagerEventObject
>;

export type RegisterClaimManagerEventFilter =
  TypedEventFilter<RegisterClaimManagerEvent>;

export interface UpdateEndEventObject {
  saleId: string;
  endTime: BigNumber;
}
export type UpdateEndEvent = TypedEvent<
  [string, BigNumber],
  UpdateEndEventObject
>;

export type UpdateEndEventFilter = TypedEventFilter<UpdateEndEvent>;

export interface UpdateMaxQueueTimeEventObject {
  saleId: string;
  maxQueueTime: BigNumber;
}
export type UpdateMaxQueueTimeEvent = TypedEvent<
  [string, BigNumber],
  UpdateMaxQueueTimeEventObject
>;

export type UpdateMaxQueueTimeEventFilter =
  TypedEventFilter<UpdateMaxQueueTimeEvent>;

export interface UpdateMerkleRootEventObject {
  saleId: string;
  merkleRoot: string;
}
export type UpdateMerkleRootEvent = TypedEvent<
  [string, string],
  UpdateMerkleRootEventObject
>;

export type UpdateMerkleRootEventFilter =
  TypedEventFilter<UpdateMerkleRootEvent>;

export interface UpdateStartEventObject {
  saleId: string;
  startTime: BigNumber;
}
export type UpdateStartEvent = TypedEvent<
  [string, BigNumber],
  UpdateStartEventObject
>;

export type UpdateStartEventFilter = TypedEventFilter<UpdateStartEvent>;

export interface UpdateUriEventObject {
  saleId: string;
  uri: string;
}
export type UpdateUriEvent = TypedEvent<[string, string], UpdateUriEventObject>;

export type UpdateUriEventFilter = TypedEventFilter<UpdateUriEvent>;

export interface SaleManager_v_1_2 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SaleManager_v_1_2Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    VERSION(overrides?: CallOverrides): Promise<[string]>;

    _isAllowed(
      root: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      proof: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "buy(bytes32,bytes32[])"(
      saleId: PromiseOrValue<BytesLike>,
      proof: PromiseOrValue<BytesLike>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "buy(bytes32,uint256,bytes32[])"(
      saleId: PromiseOrValue<BytesLike>,
      tokenQuantity: PromiseOrValue<BigNumberish>,
      proof: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    generateRandomishValue(
      merkleRoot: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getAdmin(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getBought(
      saleId: PromiseOrValue<BytesLike>,
      userAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getClaimManager(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getDecimals(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getEndTime(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getFairQueueTime(
      saleId: PromiseOrValue<BytesLike>,
      buyer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getLatestPrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    getMaxQueueTime(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getMerkleRoot(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getPrice(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getPriceOracle(overrides?: CallOverrides): Promise<[string]>;

    getRandomValue(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getRecipient(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getSaleBuyLimit(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getSpent(
      saleId: PromiseOrValue<BytesLike>,
      userAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getStartTime(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getTotalSpent(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getUri(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getUserBuyLimit(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    isOpen(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isOver(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    nativeToPaymentToken(
      nativeValue: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    newSale(
      recipient: PromiseOrValue<string>,
      merkleRoot: PromiseOrValue<BytesLike>,
      saleBuyLimit: PromiseOrValue<BigNumberish>,
      userBuyLimit: PromiseOrValue<BigNumberish>,
      startTime: PromiseOrValue<BigNumberish>,
      endTime: PromiseOrValue<BigNumberish>,
      maxQueueTime: PromiseOrValue<BigNumberish>,
      uri: PromiseOrValue<string>,
      price: PromiseOrValue<BigNumberish>,
      decimals: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    paymentToken(overrides?: CallOverrides): Promise<[string]>;

    paymentTokenDecimals(overrides?: CallOverrides): Promise<[number]>;

    recoverERC20(
      saleId: PromiseOrValue<BytesLike>,
      tokenAddress: PromiseOrValue<string>,
      tokenAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    registerClaimManager(
      saleId: PromiseOrValue<BytesLike>,
      claimManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    saleCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    setEnd(
      saleId: PromiseOrValue<BytesLike>,
      endTime: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setMaxQueueTime(
      saleId: PromiseOrValue<BytesLike>,
      maxQueueTime: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setMerkleRoot(
      saleId: PromiseOrValue<BytesLike>,
      merkleRoot: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setStart(
      saleId: PromiseOrValue<BytesLike>,
      startTime: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setUriAndMerkleRoot(
      saleId: PromiseOrValue<BytesLike>,
      merkleRoot: PromiseOrValue<BytesLike>,
      uri: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    spentToBought(
      saleId: PromiseOrValue<BytesLike>,
      spent: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    totalSpent(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  VERSION(overrides?: CallOverrides): Promise<string>;

  _isAllowed(
    root: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    proof: PromiseOrValue<BytesLike>[],
    overrides?: CallOverrides
  ): Promise<boolean>;

  "buy(bytes32,bytes32[])"(
    saleId: PromiseOrValue<BytesLike>,
    proof: PromiseOrValue<BytesLike>[],
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "buy(bytes32,uint256,bytes32[])"(
    saleId: PromiseOrValue<BytesLike>,
    tokenQuantity: PromiseOrValue<BigNumberish>,
    proof: PromiseOrValue<BytesLike>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  generateRandomishValue(
    merkleRoot: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getAdmin(
    saleId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  getBought(
    saleId: PromiseOrValue<BytesLike>,
    userAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getClaimManager(
    saleId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  getDecimals(
    saleId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getEndTime(
    saleId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getFairQueueTime(
    saleId: PromiseOrValue<BytesLike>,
    buyer: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getLatestPrice(overrides?: CallOverrides): Promise<BigNumber>;

  getMaxQueueTime(
    saleId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getMerkleRoot(
    saleId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  getPrice(
    saleId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPriceOracle(overrides?: CallOverrides): Promise<string>;

  getRandomValue(
    saleId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getRecipient(
    saleId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  getSaleBuyLimit(
    saleId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getSpent(
    saleId: PromiseOrValue<BytesLike>,
    userAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getStartTime(
    saleId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getTotalSpent(
    saleId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getUri(
    saleId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  getUserBuyLimit(
    saleId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  isOpen(
    saleId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isOver(
    saleId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  nativeToPaymentToken(
    nativeValue: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  newSale(
    recipient: PromiseOrValue<string>,
    merkleRoot: PromiseOrValue<BytesLike>,
    saleBuyLimit: PromiseOrValue<BigNumberish>,
    userBuyLimit: PromiseOrValue<BigNumberish>,
    startTime: PromiseOrValue<BigNumberish>,
    endTime: PromiseOrValue<BigNumberish>,
    maxQueueTime: PromiseOrValue<BigNumberish>,
    uri: PromiseOrValue<string>,
    price: PromiseOrValue<BigNumberish>,
    decimals: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  paymentToken(overrides?: CallOverrides): Promise<string>;

  paymentTokenDecimals(overrides?: CallOverrides): Promise<number>;

  recoverERC20(
    saleId: PromiseOrValue<BytesLike>,
    tokenAddress: PromiseOrValue<string>,
    tokenAmount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  registerClaimManager(
    saleId: PromiseOrValue<BytesLike>,
    claimManager: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  saleCount(overrides?: CallOverrides): Promise<BigNumber>;

  setEnd(
    saleId: PromiseOrValue<BytesLike>,
    endTime: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setMaxQueueTime(
    saleId: PromiseOrValue<BytesLike>,
    maxQueueTime: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setMerkleRoot(
    saleId: PromiseOrValue<BytesLike>,
    merkleRoot: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setStart(
    saleId: PromiseOrValue<BytesLike>,
    startTime: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setUriAndMerkleRoot(
    saleId: PromiseOrValue<BytesLike>,
    merkleRoot: PromiseOrValue<BytesLike>,
    uri: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  spentToBought(
    saleId: PromiseOrValue<BytesLike>,
    spent: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  totalSpent(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    VERSION(overrides?: CallOverrides): Promise<string>;

    _isAllowed(
      root: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      proof: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<boolean>;

    "buy(bytes32,bytes32[])"(
      saleId: PromiseOrValue<BytesLike>,
      proof: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<void>;

    "buy(bytes32,uint256,bytes32[])"(
      saleId: PromiseOrValue<BytesLike>,
      tokenQuantity: PromiseOrValue<BigNumberish>,
      proof: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<void>;

    generateRandomishValue(
      merkleRoot: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAdmin(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    getBought(
      saleId: PromiseOrValue<BytesLike>,
      userAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getClaimManager(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    getDecimals(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEndTime(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFairQueueTime(
      saleId: PromiseOrValue<BytesLike>,
      buyer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLatestPrice(overrides?: CallOverrides): Promise<BigNumber>;

    getMaxQueueTime(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMerkleRoot(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    getPrice(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPriceOracle(overrides?: CallOverrides): Promise<string>;

    getRandomValue(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRecipient(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    getSaleBuyLimit(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSpent(
      saleId: PromiseOrValue<BytesLike>,
      userAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getStartTime(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTotalSpent(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUri(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    getUserBuyLimit(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isOpen(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isOver(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    nativeToPaymentToken(
      nativeValue: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    newSale(
      recipient: PromiseOrValue<string>,
      merkleRoot: PromiseOrValue<BytesLike>,
      saleBuyLimit: PromiseOrValue<BigNumberish>,
      userBuyLimit: PromiseOrValue<BigNumberish>,
      startTime: PromiseOrValue<BigNumberish>,
      endTime: PromiseOrValue<BigNumberish>,
      maxQueueTime: PromiseOrValue<BigNumberish>,
      uri: PromiseOrValue<string>,
      price: PromiseOrValue<BigNumberish>,
      decimals: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    paymentToken(overrides?: CallOverrides): Promise<string>;

    paymentTokenDecimals(overrides?: CallOverrides): Promise<number>;

    recoverERC20(
      saleId: PromiseOrValue<BytesLike>,
      tokenAddress: PromiseOrValue<string>,
      tokenAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    registerClaimManager(
      saleId: PromiseOrValue<BytesLike>,
      claimManager: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    saleCount(overrides?: CallOverrides): Promise<BigNumber>;

    setEnd(
      saleId: PromiseOrValue<BytesLike>,
      endTime: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setMaxQueueTime(
      saleId: PromiseOrValue<BytesLike>,
      maxQueueTime: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setMerkleRoot(
      saleId: PromiseOrValue<BytesLike>,
      merkleRoot: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    setStart(
      saleId: PromiseOrValue<BytesLike>,
      startTime: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setUriAndMerkleRoot(
      saleId: PromiseOrValue<BytesLike>,
      merkleRoot: PromiseOrValue<BytesLike>,
      uri: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    spentToBought(
      saleId: PromiseOrValue<BytesLike>,
      spent: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalSpent(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "Buy(bytes32,address,uint256,bool,bytes32[])"(
      saleId?: PromiseOrValue<BytesLike> | null,
      buyer?: PromiseOrValue<string> | null,
      value?: null,
      native?: null,
      proof?: null
    ): BuyEventFilter;
    Buy(
      saleId?: PromiseOrValue<BytesLike> | null,
      buyer?: PromiseOrValue<string> | null,
      value?: null,
      native?: null,
      proof?: null
    ): BuyEventFilter;

    "Deploy(address,uint8,address)"(
      paymentToken?: null,
      paymentTokenDecimals?: null,
      priceOracle?: null
    ): DeployEventFilter;
    Deploy(
      paymentToken?: null,
      paymentTokenDecimals?: null,
      priceOracle?: null
    ): DeployEventFilter;

    "NewSale(bytes32,bytes32,address,address,uint256,uint256,uint256,uint256,uint256,string,uint256,uint8)"(
      saleId?: PromiseOrValue<BytesLike> | null,
      merkleRoot?: PromiseOrValue<BytesLike> | null,
      recipient?: PromiseOrValue<string> | null,
      admin?: null,
      saleBuyLimit?: null,
      userBuyLimit?: null,
      maxQueueTime?: null,
      startTime?: null,
      endTime?: null,
      uri?: null,
      price?: null,
      decimals?: null
    ): NewSaleEventFilter;
    NewSale(
      saleId?: PromiseOrValue<BytesLike> | null,
      merkleRoot?: PromiseOrValue<BytesLike> | null,
      recipient?: PromiseOrValue<string> | null,
      admin?: null,
      saleBuyLimit?: null,
      userBuyLimit?: null,
      maxQueueTime?: null,
      startTime?: null,
      endTime?: null,
      uri?: null,
      price?: null,
      decimals?: null
    ): NewSaleEventFilter;

    "RegisterClaimManager(bytes32,address)"(
      saleId?: PromiseOrValue<BytesLike> | null,
      claimManager?: PromiseOrValue<string> | null
    ): RegisterClaimManagerEventFilter;
    RegisterClaimManager(
      saleId?: PromiseOrValue<BytesLike> | null,
      claimManager?: PromiseOrValue<string> | null
    ): RegisterClaimManagerEventFilter;

    "UpdateEnd(bytes32,uint256)"(
      saleId?: PromiseOrValue<BytesLike> | null,
      endTime?: null
    ): UpdateEndEventFilter;
    UpdateEnd(
      saleId?: PromiseOrValue<BytesLike> | null,
      endTime?: null
    ): UpdateEndEventFilter;

    "UpdateMaxQueueTime(bytes32,uint256)"(
      saleId?: PromiseOrValue<BytesLike> | null,
      maxQueueTime?: null
    ): UpdateMaxQueueTimeEventFilter;
    UpdateMaxQueueTime(
      saleId?: PromiseOrValue<BytesLike> | null,
      maxQueueTime?: null
    ): UpdateMaxQueueTimeEventFilter;

    "UpdateMerkleRoot(bytes32,bytes32)"(
      saleId?: PromiseOrValue<BytesLike> | null,
      merkleRoot?: null
    ): UpdateMerkleRootEventFilter;
    UpdateMerkleRoot(
      saleId?: PromiseOrValue<BytesLike> | null,
      merkleRoot?: null
    ): UpdateMerkleRootEventFilter;

    "UpdateStart(bytes32,uint256)"(
      saleId?: PromiseOrValue<BytesLike> | null,
      startTime?: null
    ): UpdateStartEventFilter;
    UpdateStart(
      saleId?: PromiseOrValue<BytesLike> | null,
      startTime?: null
    ): UpdateStartEventFilter;

    "UpdateUri(bytes32,string)"(
      saleId?: PromiseOrValue<BytesLike> | null,
      uri?: null
    ): UpdateUriEventFilter;
    UpdateUri(
      saleId?: PromiseOrValue<BytesLike> | null,
      uri?: null
    ): UpdateUriEventFilter;
  };

  estimateGas: {
    VERSION(overrides?: CallOverrides): Promise<BigNumber>;

    _isAllowed(
      root: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      proof: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "buy(bytes32,bytes32[])"(
      saleId: PromiseOrValue<BytesLike>,
      proof: PromiseOrValue<BytesLike>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "buy(bytes32,uint256,bytes32[])"(
      saleId: PromiseOrValue<BytesLike>,
      tokenQuantity: PromiseOrValue<BigNumberish>,
      proof: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    generateRandomishValue(
      merkleRoot: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAdmin(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBought(
      saleId: PromiseOrValue<BytesLike>,
      userAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getClaimManager(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getDecimals(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEndTime(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFairQueueTime(
      saleId: PromiseOrValue<BytesLike>,
      buyer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLatestPrice(overrides?: CallOverrides): Promise<BigNumber>;

    getMaxQueueTime(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMerkleRoot(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPrice(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPriceOracle(overrides?: CallOverrides): Promise<BigNumber>;

    getRandomValue(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRecipient(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSaleBuyLimit(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSpent(
      saleId: PromiseOrValue<BytesLike>,
      userAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getStartTime(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTotalSpent(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUri(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUserBuyLimit(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isOpen(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isOver(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    nativeToPaymentToken(
      nativeValue: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    newSale(
      recipient: PromiseOrValue<string>,
      merkleRoot: PromiseOrValue<BytesLike>,
      saleBuyLimit: PromiseOrValue<BigNumberish>,
      userBuyLimit: PromiseOrValue<BigNumberish>,
      startTime: PromiseOrValue<BigNumberish>,
      endTime: PromiseOrValue<BigNumberish>,
      maxQueueTime: PromiseOrValue<BigNumberish>,
      uri: PromiseOrValue<string>,
      price: PromiseOrValue<BigNumberish>,
      decimals: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    paymentToken(overrides?: CallOverrides): Promise<BigNumber>;

    paymentTokenDecimals(overrides?: CallOverrides): Promise<BigNumber>;

    recoverERC20(
      saleId: PromiseOrValue<BytesLike>,
      tokenAddress: PromiseOrValue<string>,
      tokenAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    registerClaimManager(
      saleId: PromiseOrValue<BytesLike>,
      claimManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    saleCount(overrides?: CallOverrides): Promise<BigNumber>;

    setEnd(
      saleId: PromiseOrValue<BytesLike>,
      endTime: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setMaxQueueTime(
      saleId: PromiseOrValue<BytesLike>,
      maxQueueTime: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setMerkleRoot(
      saleId: PromiseOrValue<BytesLike>,
      merkleRoot: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setStart(
      saleId: PromiseOrValue<BytesLike>,
      startTime: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setUriAndMerkleRoot(
      saleId: PromiseOrValue<BytesLike>,
      merkleRoot: PromiseOrValue<BytesLike>,
      uri: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    spentToBought(
      saleId: PromiseOrValue<BytesLike>,
      spent: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalSpent(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    VERSION(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _isAllowed(
      root: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      proof: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "buy(bytes32,bytes32[])"(
      saleId: PromiseOrValue<BytesLike>,
      proof: PromiseOrValue<BytesLike>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "buy(bytes32,uint256,bytes32[])"(
      saleId: PromiseOrValue<BytesLike>,
      tokenQuantity: PromiseOrValue<BigNumberish>,
      proof: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    generateRandomishValue(
      merkleRoot: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAdmin(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBought(
      saleId: PromiseOrValue<BytesLike>,
      userAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getClaimManager(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDecimals(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEndTime(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFairQueueTime(
      saleId: PromiseOrValue<BytesLike>,
      buyer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLatestPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getMaxQueueTime(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMerkleRoot(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPrice(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPriceOracle(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getRandomValue(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRecipient(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSaleBuyLimit(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSpent(
      saleId: PromiseOrValue<BytesLike>,
      userAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getStartTime(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTotalSpent(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUri(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUserBuyLimit(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isOpen(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isOver(
      saleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    nativeToPaymentToken(
      nativeValue: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    newSale(
      recipient: PromiseOrValue<string>,
      merkleRoot: PromiseOrValue<BytesLike>,
      saleBuyLimit: PromiseOrValue<BigNumberish>,
      userBuyLimit: PromiseOrValue<BigNumberish>,
      startTime: PromiseOrValue<BigNumberish>,
      endTime: PromiseOrValue<BigNumberish>,
      maxQueueTime: PromiseOrValue<BigNumberish>,
      uri: PromiseOrValue<string>,
      price: PromiseOrValue<BigNumberish>,
      decimals: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    paymentToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    paymentTokenDecimals(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    recoverERC20(
      saleId: PromiseOrValue<BytesLike>,
      tokenAddress: PromiseOrValue<string>,
      tokenAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    registerClaimManager(
      saleId: PromiseOrValue<BytesLike>,
      claimManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    saleCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setEnd(
      saleId: PromiseOrValue<BytesLike>,
      endTime: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setMaxQueueTime(
      saleId: PromiseOrValue<BytesLike>,
      maxQueueTime: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setMerkleRoot(
      saleId: PromiseOrValue<BytesLike>,
      merkleRoot: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setStart(
      saleId: PromiseOrValue<BytesLike>,
      startTime: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setUriAndMerkleRoot(
      saleId: PromiseOrValue<BytesLike>,
      merkleRoot: PromiseOrValue<BytesLike>,
      uri: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    spentToBought(
      saleId: PromiseOrValue<BytesLike>,
      spent: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalSpent(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
