/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { FakeUSDC__factory } from "./FakeUSDC__factory";
export { FakeUSDT__factory } from "./FakeUSDT__factory";
export { GenericERC20__factory } from "./GenericERC20__factory";
