/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ICrosschain__factory } from "./ICrosschain__factory";
export { ICrosschainBase__factory } from "./ICrosschainBase__factory";
