/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPriceTierVesting,
  IPriceTierVestingInterface,
} from "../../../contracts/interfaces/IPriceTierVesting";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "start",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "end",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "contract AggregatorV3Interface",
        name: "oracle",
        type: "address",
      },
      {
        components: [
          {
            internalType: "uint128",
            name: "price",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "vestedFraction",
            type: "uint128",
          },
        ],
        indexed: false,
        internalType: "struct PriceTier[]",
        name: "tiers",
        type: "tuple[]",
      },
    ],
    name: "SetPriceTierConfig",
    type: "event",
  },
  {
    inputs: [],
    name: "getEnd",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getOracle",
    outputs: [
      {
        internalType: "contract AggregatorV3Interface",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "i",
        type: "uint256",
      },
    ],
    name: "getPriceTier",
    outputs: [
      {
        components: [
          {
            internalType: "uint128",
            name: "price",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "vestedFraction",
            type: "uint128",
          },
        ],
        internalType: "struct PriceTier",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getPriceTiers",
    outputs: [
      {
        components: [
          {
            internalType: "uint128",
            name: "price",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "vestedFraction",
            type: "uint128",
          },
        ],
        internalType: "struct PriceTier[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getStart",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_start",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_end",
        type: "uint256",
      },
      {
        internalType: "contract AggregatorV3Interface",
        name: "_oracle",
        type: "address",
      },
      {
        components: [
          {
            internalType: "uint128",
            name: "price",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "vestedFraction",
            type: "uint128",
          },
        ],
        internalType: "struct PriceTier[]",
        name: "_tiers",
        type: "tuple[]",
      },
    ],
    name: "setPriceTiers",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IPriceTierVesting__factory {
  static readonly abi = _abi;
  static createInterface(): IPriceTierVestingInterface {
    return new utils.Interface(_abi) as IPriceTierVestingInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPriceTierVesting {
    return new Contract(address, _abi, signerOrProvider) as IPriceTierVesting;
  }
}
